// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfOJ5k-gm27wRlzPfNVAxKBDeWQBGrPRw',
    appId: '1:42049923887:web:3b52aa0357bf13b6f5cfda',
    messagingSenderId: '42049923887',
    projectId: 'dating-app-ab2d9',
    authDomain: 'dating-app-ab2d9.firebaseapp.com',
    storageBucket: 'dating-app-ab2d9.firebasestorage.app',
    measurementId: 'G-M11HP82VYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd7g9YrD0VC4euOge-mblnXs1fD4SHyAY',
    appId: '1:42049923887:android:85099ea2588d9decf5cfda',
    messagingSenderId: '42049923887',
    projectId: 'dating-app-ab2d9',
    storageBucket: 'dating-app-ab2d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNPXSLlOIt83eS8TwTeqFpCemTRZZ0Tb4',
    appId: '1:42049923887:ios:6790ef3f850293d9f5cfda',
    messagingSenderId: '42049923887',
    projectId: 'dating-app-ab2d9',
    storageBucket: 'dating-app-ab2d9.firebasestorage.app',
    iosClientId: '42049923887-4deuo428vlo33ejn65rffeo8db62hq1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.itoBound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNPXSLlOIt83eS8TwTeqFpCemTRZZ0Tb4',
    appId: '1:42049923887:ios:6790ef3f850293d9f5cfda',
    messagingSenderId: '42049923887',
    projectId: 'dating-app-ab2d9',
    storageBucket: 'dating-app-ab2d9.firebasestorage.app',
    iosClientId: '42049923887-4deuo428vlo33ejn65rffeo8db62hq1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.itoBound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfOJ5k-gm27wRlzPfNVAxKBDeWQBGrPRw',
    appId: '1:42049923887:web:fdbad3604ce3333ef5cfda',
    messagingSenderId: '42049923887',
    projectId: 'dating-app-ab2d9',
    authDomain: 'dating-app-ab2d9.firebaseapp.com',
    storageBucket: 'dating-app-ab2d9.firebasestorage.app',
    measurementId: 'G-EYXJFV66MS',
  );

}